version: "2.3"

services:
  web:
    build: .
    links:
      - "db:postgres"
    ports:
      - "8000:80"
    volumes:
      - ".:/app2:rw"
      - "./data:/data:rw"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/db
    command: php /app/artisan serve --host 0.0.0.0 --port=80
    env_file: .env-local

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: "db"
    volumes:
      - ".:/app:rw"
