version: "2.3"

services:
  web:
    build: .
    links:
      - "db:postgres"
    ports:
      - "8000:80"
    volumes:
      - "./src:/app:rw"
      - "./src/data:/data:rw"
    depends_on:
      - db
    environment:
      - DEFAULT_DATABASE_DSN=postgres://postgres@db:5432/db
    #command: php /app/artisan serve --host 0.0.0.0 --port=80
    env_file: .env-local

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: "db"
